-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity AES_ECB_encrypt_Cipher is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_r_ce0 : OUT STD_LOGIC;
    buf_r_we0 : OUT STD_LOGIC;
    buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_r_ce1 : OUT STD_LOGIC;
    buf_r_we1 : OUT STD_LOGIC;
    buf_r_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    RoundKey_val : IN STD_LOGIC_VECTOR (1535 downto 0) );
end;


architecture behav of AES_ECB_encrypt_Cipher is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (34 downto 0) := "00000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (34 downto 0) := "00000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (34 downto 0) := "00000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (34 downto 0) := "00000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (34 downto 0) := "00000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (34 downto 0) := "00000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (34 downto 0) := "00001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (34 downto 0) := "00010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (34 downto 0) := "00100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (34 downto 0) := "01000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (34 downto 0) := "10000000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001001";
    constant ap_const_lv64_D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001101";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_E : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001110";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001111";
    constant ap_const_lv64_B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001011";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sbox_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce0 : STD_LOGIC;
    signal sbox_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_248 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal reg_253 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state29 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state29 : signal is "none";
    signal reg_260 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal reg_265 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_270 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal reg_275 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_280 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state27 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state27 : signal is "none";
    signal reg_285 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_290 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal buf_r_addr_reg_376 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal buf_r_addr_1_reg_381 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_2_reg_386 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_3_reg_391 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_4_reg_396 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_5_reg_401 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_6_reg_406 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_7_reg_411 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_8_reg_416 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_9_reg_421 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_10_reg_426 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_addr_11_reg_431 : STD_LOGIC_VECTOR (3 downto 0);
    signal round_1_reg_436 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_we0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_we0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_sbox_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_sbox_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_we0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_we1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_we0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_we0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_sbox_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_sbox_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_we0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state34 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state34 : signal is "none";
    signal ap_CS_fsm_state35 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state35 : signal is "none";
    signal round_fu_68 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln424_fu_327_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln428_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge_fu_72 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal storemerge1_fu_76 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal buf_r_ce1_local : STD_LOGIC;
    signal buf_r_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_ce0_local : STD_LOGIC;
    signal buf_r_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_we1_local : STD_LOGIC;
    signal buf_r_d1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_we0_local : STD_LOGIC;
    signal buf_r_d0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal ap_CS_fsm_state30 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state30 : signal is "none";
    signal ap_CS_fsm_state31 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state31 : signal is "none";
    signal ap_CS_fsm_state32 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state32 : signal is "none";
    signal ap_CS_fsm_state33 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state33 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (34 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_we0 : OUT STD_LOGIC;
        buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        RoundKey_val : IN STD_LOGIC_VECTOR (1535 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_we0 : OUT STD_LOGIC;
        buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce0 : OUT STD_LOGIC;
        sbox_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_304_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_we0 : OUT STD_LOGIC;
        buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_we1 : OUT STD_LOGIC;
        buf_r_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_we0 : OUT STD_LOGIC;
        buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        round : IN STD_LOGIC_VECTOR (3 downto 0);
        RoundKey_val : IN STD_LOGIC_VECTOR (1535 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_we0 : OUT STD_LOGIC;
        buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce0 : OUT STD_LOGIC;
        sbox_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_we0 : OUT STD_LOGIC;
        buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        RoundKey_val : IN STD_LOGIC_VECTOR (1535 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_sbox_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    sbox_U : component AES_ECB_encrypt_Cipher_sbox_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sbox_address0,
        ce0 => sbox_ce0,
        q0 => sbox_q0);

    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_ready,
        buf_r_address0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_address0,
        buf_r_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_ce0,
        buf_r_we0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_we0,
        buf_r_d0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_d0,
        buf_r_address1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_address1,
        buf_r_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_ce1,
        buf_r_q1 => buf_r_q1,
        RoundKey_val => RoundKey_val);

    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_ready,
        buf_r_address0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_address0,
        buf_r_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_ce0,
        buf_r_we0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_we0,
        buf_r_d0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_d0,
        buf_r_address1 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_address1,
        buf_r_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_ce1,
        buf_r_q1 => buf_r_q1,
        sbox_address0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_sbox_address0,
        sbox_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_sbox_ce0,
        sbox_q0 => sbox_q0);

    grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_304_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_ready,
        buf_r_address0 => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_address0,
        buf_r_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_ce0,
        buf_r_we0 => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_we0,
        buf_r_d0 => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_d0,
        buf_r_q0 => buf_r_q0,
        buf_r_address1 => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_address1,
        buf_r_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_ce1,
        buf_r_we1 => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_we1,
        buf_r_d1 => grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_d1,
        buf_r_q1 => buf_r_q1);

    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_ready,
        buf_r_address0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_address0,
        buf_r_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_ce0,
        buf_r_we0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_we0,
        buf_r_d0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_d0,
        buf_r_address1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_address1,
        buf_r_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_ce1,
        buf_r_q1 => buf_r_q1,
        round => round_1_reg_436,
        RoundKey_val => RoundKey_val);

    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_ready,
        buf_r_address0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_address0,
        buf_r_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_ce0,
        buf_r_we0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_we0,
        buf_r_d0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_d0,
        buf_r_address1 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_address1,
        buf_r_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_ce1,
        buf_r_q1 => buf_r_q1,
        sbox_address0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_sbox_address0,
        sbox_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_sbox_ce0,
        sbox_q0 => sbox_q0);

    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_ready,
        buf_r_address0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_address0,
        buf_r_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_ce0,
        buf_r_we0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_we0,
        buf_r_d0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_d0,
        buf_r_address1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_address1,
        buf_r_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_ce1,
        buf_r_q1 => buf_r_q1,
        RoundKey_val => RoundKey_val);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state34)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    reg_253_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                reg_253 <= buf_r_q1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                reg_253 <= buf_r_q0;
            end if; 
        end if;
    end process;

    round_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                round_fu_68 <= ap_const_lv4_1;
            elsif (((icmp_ln428_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                round_fu_68 <= add_ln424_fu_327_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state6))) then
                reg_248 <= buf_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state7))) then
                reg_260 <= buf_r_q1;
                reg_265 <= buf_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state26) or (ap_const_logic_1 = ap_CS_fsm_state8))) then
                reg_270 <= buf_r_q1;
                reg_275 <= buf_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state27) or (ap_const_logic_1 = ap_CS_fsm_state9))) then
                reg_280 <= buf_r_q1;
                reg_285 <= buf_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state28) or (ap_const_logic_1 = ap_CS_fsm_state10))) then
                reg_290 <= buf_r_q0;
                storemerge_fu_72 <= buf_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                round_1_reg_436 <= round_fu_68;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11))) then
                storemerge1_fu_76 <= buf_r_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state16, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_done, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_done, grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_done, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_done, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_done, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state18, ap_CS_fsm_state20, ap_CS_fsm_state22, ap_CS_fsm_state35, icmp_ln428_fu_321_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                if (((icmp_ln428_fu_321_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state34;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                if (((grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                if (((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                if (((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state22))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_state22;
                end if;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                if (((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state35))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state35;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln424_fu_327_p2 <= std_logic_vector(unsigned(round_fu_68) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state27 <= ap_CS_fsm(26);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state29 <= ap_CS_fsm(28);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state30 <= ap_CS_fsm(29);
    ap_CS_fsm_state31 <= ap_CS_fsm(30);
    ap_CS_fsm_state32 <= ap_CS_fsm(31);
    ap_CS_fsm_state33 <= ap_CS_fsm(32);
    ap_CS_fsm_state34 <= ap_CS_fsm(33);
    ap_CS_fsm_state35 <= ap_CS_fsm(34);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;

    ap_ST_fsm_state18_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state18_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state18_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state20_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state20_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state20_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state21_blk <= ap_const_logic_0;

    ap_ST_fsm_state22_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state22_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state22_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;

    ap_ST_fsm_state35_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state35_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state35_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done, ap_CS_fsm_state35)
    begin
        if ((((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state35)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done, ap_CS_fsm_state35)
    begin
        if (((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state35))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    buf_r_addr_10_reg_426 <= ap_const_lv64_B(4 - 1 downto 0);
    buf_r_addr_11_reg_431 <= ap_const_lv64_7(4 - 1 downto 0);
    buf_r_addr_1_reg_381 <= ap_const_lv64_5(4 - 1 downto 0);
    buf_r_addr_2_reg_386 <= ap_const_lv64_9(4 - 1 downto 0);
    buf_r_addr_3_reg_391 <= ap_const_lv64_D(4 - 1 downto 0);
    buf_r_addr_4_reg_396 <= ap_const_lv64_2(4 - 1 downto 0);
    buf_r_addr_5_reg_401 <= ap_const_lv64_A(4 - 1 downto 0);
    buf_r_addr_6_reg_406 <= ap_const_lv64_6(4 - 1 downto 0);
    buf_r_addr_7_reg_411 <= ap_const_lv64_E(4 - 1 downto 0);
    buf_r_addr_8_reg_416 <= ap_const_lv64_3(4 - 1 downto 0);
    buf_r_addr_9_reg_421 <= ap_const_lv64_F(4 - 1 downto 0);
    buf_r_addr_reg_376 <= ap_const_lv64_1(4 - 1 downto 0);

    buf_r_address0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_address0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_address0, grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_address0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_address0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_address0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state18, ap_CS_fsm_state20, ap_CS_fsm_state22, ap_CS_fsm_state35, buf_r_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            buf_r_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_address0;
        else 
            buf_r_address0 <= buf_r_address0_local;
        end if; 
    end process;


    buf_r_address0_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state24, ap_CS_fsm_state11, ap_CS_fsm_state29, ap_CS_fsm_state7, ap_CS_fsm_state25, ap_CS_fsm_state8, ap_CS_fsm_state26, ap_CS_fsm_state9, ap_CS_fsm_state27, ap_CS_fsm_state10, ap_CS_fsm_state28, ap_CS_fsm_state5, buf_r_addr_1_reg_381, buf_r_addr_3_reg_391, buf_r_addr_5_reg_401, buf_r_addr_7_reg_411, buf_r_addr_9_reg_421, buf_r_addr_11_reg_431, ap_CS_fsm_state16, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state23, ap_CS_fsm_state30, ap_CS_fsm_state31, ap_CS_fsm_state32, ap_CS_fsm_state33)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state28))) then 
            buf_r_address0_local <= buf_r_addr_11_reg_431;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state27))) then 
            buf_r_address0_local <= buf_r_addr_9_reg_421;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state32) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state26))) then 
            buf_r_address0_local <= buf_r_addr_7_reg_411;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state25))) then 
            buf_r_address0_local <= buf_r_addr_5_reg_401;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            buf_r_address0_local <= buf_r_addr_3_reg_391;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state23))) then 
            buf_r_address0_local <= buf_r_addr_1_reg_381;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            buf_r_address0_local <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            buf_r_address0_local <= ap_const_lv64_F(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_r_address0_local <= ap_const_lv64_E(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_r_address0_local <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buf_r_address0_local <= ap_const_lv64_D(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_r_address0_local <= ap_const_lv64_5(4 - 1 downto 0);
        else 
            buf_r_address0_local <= "XXXX";
        end if; 
    end process;


    buf_r_address1_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_address1, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_address1, grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_address1, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_address1, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_address1, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_address1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state18, ap_CS_fsm_state20, ap_CS_fsm_state22, ap_CS_fsm_state35, buf_r_address1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            buf_r_address1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_address1 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_address1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_address1 <= grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_address1 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_address1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_address1;
        else 
            buf_r_address1 <= buf_r_address1_local;
        end if; 
    end process;


    buf_r_address1_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state24, ap_CS_fsm_state11, ap_CS_fsm_state29, ap_CS_fsm_state7, ap_CS_fsm_state25, ap_CS_fsm_state8, ap_CS_fsm_state26, ap_CS_fsm_state9, ap_CS_fsm_state27, ap_CS_fsm_state10, ap_CS_fsm_state28, buf_r_addr_reg_376, ap_CS_fsm_state5, buf_r_addr_2_reg_386, buf_r_addr_4_reg_396, buf_r_addr_6_reg_406, buf_r_addr_8_reg_416, buf_r_addr_10_reg_426, ap_CS_fsm_state16, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state23, ap_CS_fsm_state30, ap_CS_fsm_state31, ap_CS_fsm_state32, ap_CS_fsm_state33)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state28))) then 
            buf_r_address1_local <= buf_r_addr_10_reg_426;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state27))) then 
            buf_r_address1_local <= buf_r_addr_8_reg_416;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state32) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state26))) then 
            buf_r_address1_local <= buf_r_addr_6_reg_406;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state25))) then 
            buf_r_address1_local <= buf_r_addr_4_reg_396;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            buf_r_address1_local <= buf_r_addr_2_reg_386;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state23))) then 
            buf_r_address1_local <= buf_r_addr_reg_376;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            buf_r_address1_local <= ap_const_lv64_B(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            buf_r_address1_local <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_r_address1_local <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_r_address1_local <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buf_r_address1_local <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_r_address1_local <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            buf_r_address1_local <= "XXXX";
        end if; 
    end process;


    buf_r_ce0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_ce0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_ce0, grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_ce0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_ce0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_ce0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state18, ap_CS_fsm_state20, ap_CS_fsm_state22, ap_CS_fsm_state35, buf_r_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            buf_r_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_ce0;
        else 
            buf_r_ce0 <= buf_r_ce0_local;
        end if; 
    end process;


    buf_r_ce0_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state24, ap_CS_fsm_state11, ap_CS_fsm_state29, ap_CS_fsm_state7, ap_CS_fsm_state25, ap_CS_fsm_state8, ap_CS_fsm_state26, ap_CS_fsm_state9, ap_CS_fsm_state27, ap_CS_fsm_state10, ap_CS_fsm_state28, ap_CS_fsm_state5, ap_CS_fsm_state16, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state23, ap_CS_fsm_state30, ap_CS_fsm_state31, ap_CS_fsm_state32, ap_CS_fsm_state33)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state32) or (ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state28) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state27) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state26) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            buf_r_ce0_local <= ap_const_logic_1;
        else 
            buf_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    buf_r_ce1_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_ce1, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_ce1, grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_ce1, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_ce1, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_ce1, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_ce1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state18, ap_CS_fsm_state20, ap_CS_fsm_state22, ap_CS_fsm_state35, buf_r_ce1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            buf_r_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_ce1;
        else 
            buf_r_ce1 <= buf_r_ce1_local;
        end if; 
    end process;


    buf_r_ce1_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state24, ap_CS_fsm_state11, ap_CS_fsm_state29, ap_CS_fsm_state7, ap_CS_fsm_state25, ap_CS_fsm_state8, ap_CS_fsm_state26, ap_CS_fsm_state9, ap_CS_fsm_state27, ap_CS_fsm_state10, ap_CS_fsm_state28, ap_CS_fsm_state5, ap_CS_fsm_state16, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state23, ap_CS_fsm_state30, ap_CS_fsm_state31, ap_CS_fsm_state32, ap_CS_fsm_state33)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state32) or (ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state28) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state27) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state26) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            buf_r_ce1_local <= ap_const_logic_1;
        else 
            buf_r_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    buf_r_d0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_d0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_d0, grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_d0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_d0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_d0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_d0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state18, ap_CS_fsm_state20, ap_CS_fsm_state22, ap_CS_fsm_state35, buf_r_d0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            buf_r_d0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_d0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_d0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_d0 <= grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_d0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_d0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_d0;
        else 
            buf_r_d0 <= buf_r_d0_local;
        end if; 
    end process;


    buf_r_d0_local_assign_proc : process(reg_248, reg_253, ap_CS_fsm_state11, ap_CS_fsm_state29, reg_260, reg_270, reg_280, ap_CS_fsm_state16, storemerge_fu_72, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state30, ap_CS_fsm_state31, ap_CS_fsm_state32, ap_CS_fsm_state33)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            buf_r_d0_local <= storemerge_fu_72;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state15))) then 
            buf_r_d0_local <= reg_253;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state32) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            buf_r_d0_local <= reg_280;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            buf_r_d0_local <= reg_270;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            buf_r_d0_local <= reg_248;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            buf_r_d0_local <= reg_260;
        else 
            buf_r_d0_local <= "XXXXXXXX";
        end if; 
    end process;


    buf_r_d1_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_d1, ap_CS_fsm_state18, buf_r_d1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_d1 <= grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_d1;
        else 
            buf_r_d1 <= buf_r_d1_local;
        end if; 
    end process;


    buf_r_d1_local_assign_proc : process(reg_253, ap_CS_fsm_state11, ap_CS_fsm_state29, reg_265, reg_275, reg_285, reg_290, ap_CS_fsm_state16, storemerge1_fu_76, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state30, ap_CS_fsm_state31, ap_CS_fsm_state32, ap_CS_fsm_state33)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            buf_r_d1_local <= storemerge1_fu_76;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state15))) then 
            buf_r_d1_local <= reg_290;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state32) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            buf_r_d1_local <= reg_285;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            buf_r_d1_local <= reg_275;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            buf_r_d1_local <= reg_265;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            buf_r_d1_local <= reg_253;
        else 
            buf_r_d1_local <= "XXXXXXXX";
        end if; 
    end process;


    buf_r_we0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_we0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_we0, grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_we0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_we0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_we0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_we0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state18, ap_CS_fsm_state20, ap_CS_fsm_state22, ap_CS_fsm_state35, buf_r_we0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            buf_r_we0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_buf_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_we0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_buf_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_we0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_buf_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_we0 <= grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_we0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_buf_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_we0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_buf_r_we0;
        else 
            buf_r_we0 <= buf_r_we0_local;
        end if; 
    end process;


    buf_r_we0_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state29, ap_CS_fsm_state16, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state30, ap_CS_fsm_state31, ap_CS_fsm_state32, ap_CS_fsm_state33)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state32) or (ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            buf_r_we0_local <= ap_const_logic_1;
        else 
            buf_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;


    buf_r_we1_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_we1, ap_CS_fsm_state18, buf_r_we1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_we1 <= grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_buf_r_we1;
        else 
            buf_r_we1 <= buf_r_we1_local;
        end if; 
    end process;


    buf_r_we1_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state29, ap_CS_fsm_state16, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state30, ap_CS_fsm_state31, ap_CS_fsm_state32, ap_CS_fsm_state33)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state29) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state32) or (ap_const_logic_1 = ap_CS_fsm_state31) or (ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            buf_r_we1_local <= ap_const_logic_1;
        else 
            buf_r_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_225_ap_start_reg;
    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24_fu_241_ap_start_reg;
    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_203_ap_start_reg;
    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_ap_start_reg;
    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_ap_start_reg;
    grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_304_1_fu_219_ap_start_reg;
    icmp_ln428_fu_321_p2 <= "1" when (round_fu_68 = ap_const_lv4_A) else "0";

    sbox_address0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_sbox_address0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_sbox_address0, ap_CS_fsm_state4, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            sbox_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_sbox_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sbox_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_sbox_address0;
        else 
            sbox_address0 <= "XXXXXXXX";
        end if; 
    end process;


    sbox_ce0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_sbox_ce0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_sbox_ce0, ap_CS_fsm_state4, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            sbox_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_23_fu_233_sbox_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sbox_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_211_sbox_ce0;
        else 
            sbox_ce0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
