// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_r_address0,
        buf_r_ce0,
        buf_r_we0,
        buf_r_d0,
        buf_r_address1,
        buf_r_ce1,
        buf_r_q1,
        RoundKey_val
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] buf_r_address0;
output   buf_r_ce0;
output   buf_r_we0;
output  [7:0] buf_r_d0;
output  [3:0] buf_r_address1;
output   buf_r_ce1;
input  [7:0] buf_r_q1;
input  [1535:0] RoundKey_val;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln240_fu_103_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] select_ln239_fu_138_p3;
reg   [2:0] select_ln239_reg_268;
wire   [1:0] trunc_ln244_fu_154_p1;
reg   [1:0] trunc_ln244_reg_273;
wire   [1:0] trunc_ln244_1_fu_158_p1;
reg   [1:0] trunc_ln244_1_reg_279;
reg   [3:0] buf_r_addr_reg_284;
wire   [7:0] trunc_ln244_2_fu_228_p1;
reg   [7:0] trunc_ln244_2_reg_290;
wire   [63:0] zext_ln244_1_fu_194_p1;
wire    ap_block_pp0_stage0;
reg   [2:0] j_fu_50;
wire   [2:0] add_ln242_fu_162_p2;
wire    ap_loop_init;
reg   [2:0] i_fu_54;
wire   [2:0] select_ln240_fu_146_p3;
reg   [4:0] indvar_flatten27_fu_58;
wire   [4:0] add_ln240_fu_109_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten27_load;
reg    buf_r_ce1_local;
reg    buf_r_we0_local;
wire   [7:0] xor_ln244_fu_232_p2;
reg    buf_r_ce0_local;
wire   [0:0] icmp_ln242_fu_132_p2;
wire   [2:0] add_ln240_1_fu_126_p2;
wire   [3:0] tmp_3_fu_178_p3;
wire   [3:0] zext_ln244_fu_185_p1;
wire   [3:0] add_ln244_fu_188_p2;
wire   [3:0] tmp_fu_199_p3;
wire   [4:0] zext_ln244_2_fu_205_p1;
wire   [10:0] zext_ln244_1_cast_fu_209_p4;
wire   [1535:0] zext_ln244_3_fu_219_p1;
wire   [1535:0] lshr_ln244_fu_223_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 j_fu_50 = 3'd0;
#0 i_fu_54 = 3'd0;
#0 indvar_flatten27_fu_58 = 5'd0;
#0 ap_done_reg = 1'b0;
end

AES_ECB_encrypt_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_54 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_54 <= select_ln240_fu_146_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln240_fu_103_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten27_fu_58 <= add_ln240_fu_109_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten27_fu_58 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_50 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_50 <= add_ln242_fu_162_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln239_reg_268 <= select_ln239_fu_138_p3;
        trunc_ln244_1_reg_279 <= trunc_ln244_1_fu_158_p1;
        trunc_ln244_reg_273 <= trunc_ln244_fu_154_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        buf_r_addr_reg_284 <= zext_ln244_1_fu_194_p1;
        trunc_ln244_2_reg_290 <= trunc_ln244_2_fu_228_p1;
    end
end

always @ (*) begin
    if (((icmp_ln240_fu_103_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten27_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten27_load = indvar_flatten27_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        buf_r_ce0_local = 1'b1;
    end else begin
        buf_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_r_ce1_local = 1'b1;
    end else begin
        buf_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        buf_r_we0_local = 1'b1;
    end else begin
        buf_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln240_1_fu_126_p2 = (i_fu_54 + 3'd1);

assign add_ln240_fu_109_p2 = (ap_sig_allocacmp_indvar_flatten27_load + 5'd1);

assign add_ln242_fu_162_p2 = (select_ln239_fu_138_p3 + 3'd1);

assign add_ln244_fu_188_p2 = (tmp_3_fu_178_p3 + zext_ln244_fu_185_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buf_r_address0 = buf_r_addr_reg_284;

assign buf_r_address1 = zext_ln244_1_fu_194_p1;

assign buf_r_ce0 = buf_r_ce0_local;

assign buf_r_ce1 = buf_r_ce1_local;

assign buf_r_d0 = xor_ln244_fu_232_p2;

assign buf_r_we0 = buf_r_we0_local;

assign icmp_ln240_fu_103_p2 = ((ap_sig_allocacmp_indvar_flatten27_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln242_fu_132_p2 = ((j_fu_50 == 3'd4) ? 1'b1 : 1'b0);

assign lshr_ln244_fu_223_p2 = RoundKey_val >> zext_ln244_3_fu_219_p1;

assign select_ln239_fu_138_p3 = ((icmp_ln242_fu_132_p2[0:0] == 1'b1) ? 3'd0 : j_fu_50);

assign select_ln240_fu_146_p3 = ((icmp_ln242_fu_132_p2[0:0] == 1'b1) ? add_ln240_1_fu_126_p2 : i_fu_54);

assign tmp_3_fu_178_p3 = {{trunc_ln244_reg_273}, {2'd0}};

assign tmp_fu_199_p3 = {{trunc_ln244_reg_273}, {trunc_ln244_1_reg_279}};

assign trunc_ln244_1_fu_158_p1 = select_ln239_fu_138_p3[1:0];

assign trunc_ln244_2_fu_228_p1 = lshr_ln244_fu_223_p2[7:0];

assign trunc_ln244_fu_154_p1 = select_ln240_fu_146_p3[1:0];

assign xor_ln244_fu_232_p2 = (trunc_ln244_2_reg_290 ^ buf_r_q1);

assign zext_ln244_1_cast_fu_209_p4 = {{{{3'd5}, {zext_ln244_2_fu_205_p1}}}, {3'd0}};

assign zext_ln244_1_fu_194_p1 = add_ln244_fu_188_p2;

assign zext_ln244_2_fu_205_p1 = tmp_fu_199_p3;

assign zext_ln244_3_fu_219_p1 = zext_ln244_1_cast_fu_209_p4;

assign zext_ln244_fu_185_p1 = select_ln239_reg_268;

endmodule //AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_24
