-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity AES_ECB_encrypt_Cipher is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_r_ce0 : OUT STD_LOGIC;
    buf_r_we0 : OUT STD_LOGIC;
    buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_r_ce1 : OUT STD_LOGIC;
    buf_r_we1 : OUT STD_LOGIC;
    buf_r_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    RoundKey_val : IN STD_LOGIC_VECTOR (1535 downto 0) );
end;


architecture behav of AES_ECB_encrypt_Cipher is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (23 downto 0) := "000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (23 downto 0) := "000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (23 downto 0) := "000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (23 downto 0) := "000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (23 downto 0) := "000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (23 downto 0) := "000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (23 downto 0) := "000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (23 downto 0) := "000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (23 downto 0) := "000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (23 downto 0) := "001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (23 downto 0) := "010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001001";
    constant ap_const_lv64_D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001101";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_E : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001110";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001111";
    constant ap_const_lv64_B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001011";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv64_C : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sbox_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce0 : STD_LOGIC;
    signal sbox_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce1 : STD_LOGIC;
    signal sbox_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce2 : STD_LOGIC;
    signal sbox_q2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce3 : STD_LOGIC;
    signal sbox_q3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce4 : STD_LOGIC;
    signal sbox_q4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce5 : STD_LOGIC;
    signal sbox_q5 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce6 : STD_LOGIC;
    signal sbox_q6 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce7 : STD_LOGIC;
    signal sbox_q7 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce8 : STD_LOGIC;
    signal sbox_q8 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce9 : STD_LOGIC;
    signal sbox_q9 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce10 : STD_LOGIC;
    signal sbox_q10 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce11 : STD_LOGIC;
    signal sbox_q11 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce12 : STD_LOGIC;
    signal sbox_q12 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce13 : STD_LOGIC;
    signal sbox_q13 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce14 : STD_LOGIC;
    signal sbox_q14 : STD_LOGIC_VECTOR (7 downto 0);
    signal sbox_ce15 : STD_LOGIC;
    signal sbox_q15 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal buf_r_addr_1_reg_518 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal buf_r_addr_3_reg_529 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_reg_534 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_load_reg_539 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_addr_4_reg_544 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal buf_r_load_1_reg_555 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_load_2_reg_560 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_addr_6_reg_565 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal temp_8_reg_576 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_load_4_reg_581 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal buf_r_addr_9_reg_592 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_9_reg_597 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_load_6_reg_602 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal buf_r_addr_11_reg_613 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_10_reg_618 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_load_8_reg_623 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_addr_12_reg_628 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal buf_r_load_9_reg_639 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_load_10_reg_644 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_addr_14_reg_649 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal buf_r_load_11_reg_660 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_load_12_reg_665 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_load_13_reg_670 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal buf_r_load_14_reg_675 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_we0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_we0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out_ap_vld : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce2 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce3 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce4 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address5 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce5 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address6 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce6 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address7 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce7 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address8 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce8 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address9 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce9 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address10 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce10 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address11 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce11 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address12 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce12 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address13 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce13 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address14 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce14 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address15 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce15 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_idle : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_ready : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_we0 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce1 : STD_LOGIC;
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal buf_r_ce1_local : STD_LOGIC;
    signal buf_r_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_ce0_local : STD_LOGIC;
    signal buf_r_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_r_we1_local : STD_LOGIC;
    signal buf_r_d1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_we0_local : STD_LOGIC;
    signal buf_r_d0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_we0 : OUT STD_LOGIC;
        buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        RoundKey_val : IN STD_LOGIC_VECTOR (1535 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_we0 : OUT STD_LOGIC;
        buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce0 : OUT STD_LOGIC;
        sbox_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_424_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_load_9 : IN STD_LOGIC_VECTOR (7 downto 0);
        temp_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        temp : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_14 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_10 : IN STD_LOGIC_VECTOR (7 downto 0);
        temp_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_13 : IN STD_LOGIC_VECTOR (7 downto 0);
        temp_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_6 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_12 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_8 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_load_11 : IN STD_LOGIC_VECTOR (7 downto 0);
        RoundKey_val : IN STD_LOGIC_VECTOR (1535 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        t_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        t_3_out_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        t_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        t_2_out_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        p_out7 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out7_ap_vld : OUT STD_LOGIC;
        p_out8 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out8_ap_vld : OUT STD_LOGIC;
        t_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        t_1_out_ap_vld : OUT STD_LOGIC;
        p_out9 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out9_ap_vld : OUT STD_LOGIC;
        p_out10 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out10_ap_vld : OUT STD_LOGIC;
        p_out11 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out11_ap_vld : OUT STD_LOGIC;
        t_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        t_out_ap_vld : OUT STD_LOGIC;
        sbox_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce0 : OUT STD_LOGIC;
        sbox_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce1 : OUT STD_LOGIC;
        sbox_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce2 : OUT STD_LOGIC;
        sbox_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce3 : OUT STD_LOGIC;
        sbox_q3 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address4 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce4 : OUT STD_LOGIC;
        sbox_q4 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address5 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce5 : OUT STD_LOGIC;
        sbox_q5 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address6 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce6 : OUT STD_LOGIC;
        sbox_q6 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address7 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce7 : OUT STD_LOGIC;
        sbox_q7 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address8 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce8 : OUT STD_LOGIC;
        sbox_q8 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address9 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce9 : OUT STD_LOGIC;
        sbox_q9 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address10 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce10 : OUT STD_LOGIC;
        sbox_q10 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address11 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce11 : OUT STD_LOGIC;
        sbox_q11 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address12 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce12 : OUT STD_LOGIC;
        sbox_q12 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address13 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce13 : OUT STD_LOGIC;
        sbox_q13 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address14 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce14 : OUT STD_LOGIC;
        sbox_q14 : IN STD_LOGIC_VECTOR (7 downto 0);
        sbox_address15 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sbox_ce15 : OUT STD_LOGIC;
        sbox_q15 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_we0 : OUT STD_LOGIC;
        buf_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        RoundKey_val : IN STD_LOGIC_VECTOR (1535 downto 0) );
    end component;


    component AES_ECB_encrypt_Cipher_sbox_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address3 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address4 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address5 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce5 : IN STD_LOGIC;
        q5 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address6 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce6 : IN STD_LOGIC;
        q6 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address7 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce7 : IN STD_LOGIC;
        q7 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address8 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce8 : IN STD_LOGIC;
        q8 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address9 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce9 : IN STD_LOGIC;
        q9 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address10 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce10 : IN STD_LOGIC;
        q10 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address11 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce11 : IN STD_LOGIC;
        q11 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address12 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce12 : IN STD_LOGIC;
        q12 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address13 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce13 : IN STD_LOGIC;
        q13 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address14 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce14 : IN STD_LOGIC;
        q14 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address15 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce15 : IN STD_LOGIC;
        q15 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    sbox_U : component AES_ECB_encrypt_Cipher_sbox_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sbox_address0,
        ce0 => sbox_ce0,
        q0 => sbox_q0,
        address1 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address1,
        ce1 => sbox_ce1,
        q1 => sbox_q1,
        address2 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address2,
        ce2 => sbox_ce2,
        q2 => sbox_q2,
        address3 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address3,
        ce3 => sbox_ce3,
        q3 => sbox_q3,
        address4 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address4,
        ce4 => sbox_ce4,
        q4 => sbox_q4,
        address5 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address5,
        ce5 => sbox_ce5,
        q5 => sbox_q5,
        address6 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address6,
        ce6 => sbox_ce6,
        q6 => sbox_q6,
        address7 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address7,
        ce7 => sbox_ce7,
        q7 => sbox_q7,
        address8 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address8,
        ce8 => sbox_ce8,
        q8 => sbox_q8,
        address9 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address9,
        ce9 => sbox_ce9,
        q9 => sbox_q9,
        address10 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address10,
        ce10 => sbox_ce10,
        q10 => sbox_q10,
        address11 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address11,
        ce11 => sbox_ce11,
        q11 => sbox_q11,
        address12 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address12,
        ce12 => sbox_ce12,
        q12 => sbox_q12,
        address13 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address13,
        ce13 => sbox_ce13,
        q13 => sbox_q13,
        address14 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address14,
        ce14 => sbox_ce14,
        q14 => sbox_q14,
        address15 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address15,
        ce15 => sbox_ce15,
        q15 => sbox_q15);

    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_ready,
        buf_r_address0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address0,
        buf_r_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce0,
        buf_r_we0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_we0,
        buf_r_d0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_d0,
        buf_r_address1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address1,
        buf_r_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce1,
        buf_r_q1 => buf_r_q1,
        RoundKey_val => RoundKey_val);

    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_ready,
        buf_r_address0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address0,
        buf_r_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce0,
        buf_r_we0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_we0,
        buf_r_d0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_d0,
        buf_r_address1 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address1,
        buf_r_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce1,
        buf_r_q1 => buf_r_q1,
        sbox_address0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_address0,
        sbox_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_ce0,
        sbox_q0 => sbox_q0);

    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_424_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_ready,
        buf_r_load_9 => buf_r_load_9_reg_639,
        temp_2 => temp_9_reg_597,
        temp => temp_reg_534,
        buf_r_load_14 => buf_r_load_14_reg_675,
        buf_r_load_10 => buf_r_load_10_reg_644,
        temp_1 => temp_8_reg_576,
        buf_r_load_2 => buf_r_load_2_reg_560,
        buf_r_load_13 => buf_r_load_13_reg_670,
        temp_3 => temp_10_reg_618,
        buf_r_load_6 => buf_r_load_6_reg_602,
        buf_r_load_1 => buf_r_load_1_reg_555,
        buf_r_load_12 => buf_r_load_12_reg_665,
        buf_r_load_8 => buf_r_load_8_reg_623,
        buf_r_load_4 => buf_r_load_4_reg_581,
        buf_r_load => buf_r_load_reg_539,
        buf_r_load_11 => buf_r_load_11_reg_660,
        RoundKey_val => RoundKey_val,
        p_out => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out,
        p_out_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out_ap_vld,
        p_out1 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1,
        p_out1_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1_ap_vld,
        p_out2 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2,
        p_out2_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2_ap_vld,
        t_3_out => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out,
        t_3_out_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out_ap_vld,
        p_out3 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3,
        p_out3_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3_ap_vld,
        p_out4 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4,
        p_out4_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4_ap_vld,
        p_out5 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5,
        p_out5_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5_ap_vld,
        t_2_out => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out,
        t_2_out_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out_ap_vld,
        p_out6 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6,
        p_out6_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6_ap_vld,
        p_out7 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7,
        p_out7_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7_ap_vld,
        p_out8 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8,
        p_out8_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8_ap_vld,
        t_1_out => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out,
        t_1_out_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out_ap_vld,
        p_out9 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9,
        p_out9_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9_ap_vld,
        p_out10 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10,
        p_out10_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10_ap_vld,
        p_out11 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11,
        p_out11_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11_ap_vld,
        t_out => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out,
        t_out_ap_vld => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out_ap_vld,
        sbox_address0 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address0,
        sbox_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce0,
        sbox_q0 => sbox_q0,
        sbox_address1 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address1,
        sbox_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce1,
        sbox_q1 => sbox_q1,
        sbox_address2 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address2,
        sbox_ce2 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce2,
        sbox_q2 => sbox_q2,
        sbox_address3 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address3,
        sbox_ce3 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce3,
        sbox_q3 => sbox_q3,
        sbox_address4 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address4,
        sbox_ce4 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce4,
        sbox_q4 => sbox_q4,
        sbox_address5 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address5,
        sbox_ce5 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce5,
        sbox_q5 => sbox_q5,
        sbox_address6 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address6,
        sbox_ce6 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce6,
        sbox_q6 => sbox_q6,
        sbox_address7 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address7,
        sbox_ce7 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce7,
        sbox_q7 => sbox_q7,
        sbox_address8 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address8,
        sbox_ce8 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce8,
        sbox_q8 => sbox_q8,
        sbox_address9 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address9,
        sbox_ce9 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce9,
        sbox_q9 => sbox_q9,
        sbox_address10 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address10,
        sbox_ce10 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce10,
        sbox_q10 => sbox_q10,
        sbox_address11 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address11,
        sbox_ce11 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce11,
        sbox_q11 => sbox_q11,
        sbox_address12 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address12,
        sbox_ce12 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce12,
        sbox_q12 => sbox_q12,
        sbox_address13 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address13,
        sbox_ce13 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce13,
        sbox_q13 => sbox_q13,
        sbox_address14 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address14,
        sbox_ce14 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce14,
        sbox_q14 => sbox_q14,
        sbox_address15 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address15,
        sbox_ce15 => grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce15,
        sbox_q15 => sbox_q15);

    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338 : component AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start,
        ap_done => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done,
        ap_idle => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_idle,
        ap_ready => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_ready,
        buf_r_address0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address0,
        buf_r_ce0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce0,
        buf_r_we0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_we0,
        buf_r_d0 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_d0,
        buf_r_address1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address1,
        buf_r_ce1 => grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce1,
        buf_r_q1 => buf_r_q1,
        RoundKey_val => RoundKey_val);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                buf_r_load_10_reg_644 <= buf_r_q0;
                buf_r_load_9_reg_639 <= buf_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                buf_r_load_11_reg_660 <= buf_r_q1;
                buf_r_load_12_reg_665 <= buf_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                buf_r_load_13_reg_670 <= buf_r_q1;
                buf_r_load_14_reg_675 <= buf_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                buf_r_load_1_reg_555 <= buf_r_q1;
                buf_r_load_2_reg_560 <= buf_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                buf_r_load_4_reg_581 <= buf_r_q0;
                temp_8_reg_576 <= buf_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                buf_r_load_6_reg_602 <= buf_r_q0;
                temp_9_reg_597 <= buf_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                buf_r_load_8_reg_623 <= buf_r_q0;
                temp_10_reg_618 <= buf_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                buf_r_load_reg_539 <= buf_r_q0;
                temp_reg_534 <= buf_r_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state24)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                if (((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state24;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;

    ap_ST_fsm_state24_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state24_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state24_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done)
    begin
        if ((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done, ap_CS_fsm_state24)
    begin
        if ((((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done, ap_CS_fsm_state24)
    begin
        if (((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    buf_r_addr_11_reg_613 <= ap_const_lv64_7(4 - 1 downto 0);
    buf_r_addr_12_reg_628 <= ap_const_lv64_0(4 - 1 downto 0);
    buf_r_addr_14_reg_649 <= ap_const_lv64_8(4 - 1 downto 0);
    buf_r_addr_1_reg_518 <= ap_const_lv64_5(4 - 1 downto 0);
    buf_r_addr_3_reg_529 <= ap_const_lv64_D(4 - 1 downto 0);
    buf_r_addr_4_reg_544 <= ap_const_lv64_2(4 - 1 downto 0);
    buf_r_addr_6_reg_565 <= ap_const_lv64_6(4 - 1 downto 0);
    buf_r_addr_9_reg_592 <= ap_const_lv64_F(4 - 1 downto 0);

    buf_r_address0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state24, buf_r_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            buf_r_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address0;
        else 
            buf_r_address0 <= buf_r_address0_local;
        end if; 
    end process;


    buf_r_address0_local_assign_proc : process(ap_CS_fsm_state5, buf_r_addr_1_reg_518, ap_CS_fsm_state6, buf_r_addr_3_reg_529, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, buf_r_addr_9_reg_592, ap_CS_fsm_state10, buf_r_addr_11_reg_613, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_address0_local <= buf_r_addr_9_reg_592;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            buf_r_address0_local <= buf_r_addr_3_reg_529;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_address0_local <= ap_const_lv64_B(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            buf_r_address0_local <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_address0_local <= buf_r_addr_11_reg_613;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            buf_r_address0_local <= buf_r_addr_1_reg_518;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            buf_r_address0_local <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            buf_r_address0_local <= ap_const_lv64_1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            buf_r_address0_local <= ap_const_lv64_C(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            buf_r_address0_local <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            buf_r_address0_local <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            buf_r_address0_local <= ap_const_lv64_F(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_r_address0_local <= ap_const_lv64_E(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_r_address0_local <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buf_r_address0_local <= ap_const_lv64_D(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_r_address0_local <= ap_const_lv64_5(4 - 1 downto 0);
        else 
            buf_r_address0_local <= "XXXX";
        end if; 
    end process;


    buf_r_address1_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address1, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address1, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state24, buf_r_address1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            buf_r_address1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_address1 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_address1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address1;
        else 
            buf_r_address1 <= buf_r_address1_local;
        end if; 
    end process;


    buf_r_address1_local_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, buf_r_addr_4_reg_544, ap_CS_fsm_state7, buf_r_addr_6_reg_565, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, buf_r_addr_12_reg_628, ap_CS_fsm_state11, buf_r_addr_14_reg_649, ap_CS_fsm_state12, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_address1_local <= ap_const_lv64_E(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            buf_r_address1_local <= ap_const_lv64_C(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_address1_local <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            buf_r_address1_local <= buf_r_addr_14_reg_649;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_address1_local <= buf_r_addr_6_reg_565;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            buf_r_address1_local <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            buf_r_address1_local <= buf_r_addr_4_reg_544;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            buf_r_address1_local <= buf_r_addr_12_reg_628;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            buf_r_address1_local <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            buf_r_address1_local <= ap_const_lv64_0(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            buf_r_address1_local <= ap_const_lv64_B(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            buf_r_address1_local <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_r_address1_local <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_r_address1_local <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buf_r_address1_local <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_r_address1_local <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            buf_r_address1_local <= "XXXX";
        end if; 
    end process;


    buf_r_ce0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state24, buf_r_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            buf_r_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce0;
        else 
            buf_r_ce0 <= buf_r_ce0_local;
        end if; 
    end process;


    buf_r_ce0_local_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            buf_r_ce0_local <= ap_const_logic_1;
        else 
            buf_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    buf_r_ce1_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce1, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce1, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state24, buf_r_ce1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            buf_r_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce1;
        else 
            buf_r_ce1 <= buf_r_ce1_local;
        end if; 
    end process;


    buf_r_ce1_local_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            buf_r_ce1_local <= ap_const_logic_1;
        else 
            buf_r_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    buf_r_d0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_d0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_d0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_d0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state24, buf_r_d0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            buf_r_d0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_d0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_d0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_d0;
        else 
            buf_r_d0 <= buf_r_d0_local;
        end if; 
    end process;


    buf_r_d0_local_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_d0_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            buf_r_d0_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_d0_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            buf_r_d0_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_d0_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            buf_r_d0_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            buf_r_d0_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            buf_r_d0_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11;
        else 
            buf_r_d0_local <= "XXXXXXXX";
        end if; 
    end process;

    buf_r_d1 <= buf_r_d1_local;

    buf_r_d1_local_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            buf_r_d1_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            buf_r_d1_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            buf_r_d1_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            buf_r_d1_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            buf_r_d1_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            buf_r_d1_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            buf_r_d1_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            buf_r_d1_local <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out;
        else 
            buf_r_d1_local <= "XXXXXXXX";
        end if; 
    end process;


    buf_r_we0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_we0, grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_we0, grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_we0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state24, buf_r_we0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            buf_r_we0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_we0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_we0 <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_we0;
        else 
            buf_r_we0 <= buf_r_we0_local;
        end if; 
    end process;


    buf_r_we0_local_assign_proc : process(ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15))) then 
            buf_r_we0_local <= ap_const_logic_1;
        else 
            buf_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buf_r_we1 <= buf_r_we1_local;

    buf_r_we1_local_assign_proc : process(ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15))) then 
            buf_r_we1_local <= ap_const_logic_1;
        else 
            buf_r_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg;
    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg;
    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg;
    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg;

    sbox_address0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_address0, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sbox_address0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_address0;
        else 
            sbox_address0 <= "XXXXXXXX";
        end if; 
    end process;


    sbox_ce0_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_ce0, grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sbox_ce0 <= grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_ce0;
        else 
            sbox_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce1_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce1, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce1 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce1;
        else 
            sbox_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce10_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce10, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce10 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce10;
        else 
            sbox_ce10 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce11_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce11, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce11 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce11;
        else 
            sbox_ce11 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce12_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce12, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce12 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce12;
        else 
            sbox_ce12 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce13_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce13, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce13 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce13;
        else 
            sbox_ce13 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce14_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce14, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce14 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce14;
        else 
            sbox_ce14 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce15_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce15, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce15 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce15;
        else 
            sbox_ce15 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce2_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce2, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce2 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce2;
        else 
            sbox_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce3_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce3, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce3 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce3;
        else 
            sbox_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce4_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce4 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce4;
        else 
            sbox_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce5_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce5, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce5 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce5;
        else 
            sbox_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce6_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce6, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce6 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce6;
        else 
            sbox_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce7_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce7, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce7 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce7;
        else 
            sbox_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce8_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce8, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce8 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce8;
        else 
            sbox_ce8 <= ap_const_logic_0;
        end if; 
    end process;


    sbox_ce9_assign_proc : process(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce9, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            sbox_ce9 <= grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce9;
        else 
            sbox_ce9 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
