// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module AES_ECB_encrypt_Cipher (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_r_address0,
        buf_r_ce0,
        buf_r_we0,
        buf_r_d0,
        buf_r_q0,
        buf_r_address1,
        buf_r_ce1,
        buf_r_we1,
        buf_r_d1,
        buf_r_q1,
        RoundKey_val
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] buf_r_address0;
output   buf_r_ce0;
output   buf_r_we0;
output  [7:0] buf_r_d0;
input  [7:0] buf_r_q0;
output  [3:0] buf_r_address1;
output   buf_r_ce1;
output   buf_r_we1;
output  [7:0] buf_r_d1;
input  [7:0] buf_r_q1;
input  [1535:0] RoundKey_val;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] buf_r_address0;
reg buf_r_ce0;
reg buf_r_we0;
reg[7:0] buf_r_d0;
reg[3:0] buf_r_address1;
reg buf_r_ce1;

(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] sbox_address0;
reg    sbox_ce0;
wire   [7:0] sbox_q0;
reg    sbox_ce1;
wire   [7:0] sbox_q1;
reg    sbox_ce2;
wire   [7:0] sbox_q2;
reg    sbox_ce3;
wire   [7:0] sbox_q3;
reg    sbox_ce4;
wire   [7:0] sbox_q4;
reg    sbox_ce5;
wire   [7:0] sbox_q5;
reg    sbox_ce6;
wire   [7:0] sbox_q6;
reg    sbox_ce7;
wire   [7:0] sbox_q7;
reg    sbox_ce8;
wire   [7:0] sbox_q8;
reg    sbox_ce9;
wire   [7:0] sbox_q9;
reg    sbox_ce10;
wire   [7:0] sbox_q10;
reg    sbox_ce11;
wire   [7:0] sbox_q11;
reg    sbox_ce12;
wire   [7:0] sbox_q12;
reg    sbox_ce13;
wire   [7:0] sbox_q13;
reg    sbox_ce14;
wire   [7:0] sbox_q14;
reg    sbox_ce15;
wire   [7:0] sbox_q15;
wire    ap_CS_fsm_state5;
wire   [3:0] buf_r_addr_1_reg_518;
wire    ap_CS_fsm_state6;
wire   [3:0] buf_r_addr_3_reg_529;
reg   [7:0] temp_reg_534;
reg   [7:0] buf_r_load_reg_539;
wire   [3:0] buf_r_addr_4_reg_544;
wire    ap_CS_fsm_state7;
reg   [7:0] buf_r_load_1_reg_555;
reg   [7:0] buf_r_load_2_reg_560;
wire   [3:0] buf_r_addr_6_reg_565;
wire    ap_CS_fsm_state8;
reg   [7:0] temp_8_reg_576;
reg   [7:0] buf_r_load_4_reg_581;
wire    ap_CS_fsm_state9;
wire   [3:0] buf_r_addr_9_reg_592;
reg   [7:0] temp_9_reg_597;
reg   [7:0] buf_r_load_6_reg_602;
wire    ap_CS_fsm_state10;
wire   [3:0] buf_r_addr_11_reg_613;
reg   [7:0] temp_10_reg_618;
reg   [7:0] buf_r_load_8_reg_623;
wire   [3:0] buf_r_addr_12_reg_628;
wire    ap_CS_fsm_state11;
reg   [7:0] buf_r_load_9_reg_639;
reg   [7:0] buf_r_load_10_reg_644;
wire   [3:0] buf_r_addr_14_reg_649;
wire    ap_CS_fsm_state12;
reg   [7:0] buf_r_load_11_reg_660;
reg   [7:0] buf_r_load_12_reg_665;
reg   [7:0] buf_r_load_13_reg_670;
wire    ap_CS_fsm_state13;
reg   [7:0] buf_r_load_14_reg_675;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_idle;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_ready;
wire   [3:0] grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address0;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce0;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_we0;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_d0;
wire   [3:0] grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address1;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce1;
wire    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start;
wire    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done;
wire    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_idle;
wire    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_ready;
wire   [3:0] grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address0;
wire    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce0;
wire    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_we0;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_d0;
wire   [3:0] grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address1;
wire    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce1;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_address0;
wire    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_ce0;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_idle;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_ready;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out_ap_vld;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address0;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce0;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address1;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce1;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address2;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce2;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address3;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce3;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address4;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce4;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address5;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce5;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address6;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce6;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address7;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce7;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address8;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce8;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address9;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce9;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address10;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce10;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address11;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce11;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address12;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce12;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address13;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce13;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address14;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce14;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address15;
wire    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce15;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_idle;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_ready;
wire   [3:0] grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address0;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce0;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_we0;
wire   [7:0] grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_d0;
wire   [3:0] grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address1;
wire    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce1;
reg    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
reg    buf_r_ce1_local;
reg   [3:0] buf_r_address1_local;
reg    buf_r_ce0_local;
reg   [3:0] buf_r_address0_local;
reg    buf_r_we1_local;
reg   [7:0] buf_r_d1_local;
reg    buf_r_we0_local;
reg   [7:0] buf_r_d0_local;
reg   [23:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg = 1'b0;
#0 grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg = 1'b0;
#0 grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg = 1'b0;
#0 grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg = 1'b0;
end

AES_ECB_encrypt_Cipher_sbox_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sbox_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sbox_address0),
    .ce0(sbox_ce0),
    .q0(sbox_q0),
    .address1(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address1),
    .ce1(sbox_ce1),
    .q1(sbox_q1),
    .address2(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address2),
    .ce2(sbox_ce2),
    .q2(sbox_q2),
    .address3(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address3),
    .ce3(sbox_ce3),
    .q3(sbox_q3),
    .address4(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address4),
    .ce4(sbox_ce4),
    .q4(sbox_q4),
    .address5(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address5),
    .ce5(sbox_ce5),
    .q5(sbox_q5),
    .address6(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address6),
    .ce6(sbox_ce6),
    .q6(sbox_q6),
    .address7(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address7),
    .ce7(sbox_ce7),
    .q7(sbox_q7),
    .address8(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address8),
    .ce8(sbox_ce8),
    .q8(sbox_q8),
    .address9(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address9),
    .ce9(sbox_ce9),
    .q9(sbox_q9),
    .address10(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address10),
    .ce10(sbox_ce10),
    .q10(sbox_q10),
    .address11(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address11),
    .ce11(sbox_ce11),
    .q11(sbox_q11),
    .address12(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address12),
    .ce12(sbox_ce12),
    .q12(sbox_q12),
    .address13(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address13),
    .ce13(sbox_ce13),
    .q13(sbox_q13),
    .address14(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address14),
    .ce14(sbox_ce14),
    .q14(sbox_q14),
    .address15(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address15),
    .ce15(sbox_ce15),
    .q15(sbox_q15)
);

AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2 grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start),
    .ap_done(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done),
    .ap_idle(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_idle),
    .ap_ready(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_ready),
    .buf_r_address0(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address0),
    .buf_r_ce0(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce0),
    .buf_r_we0(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_we0),
    .buf_r_d0(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_d0),
    .buf_r_address1(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address1),
    .buf_r_ce1(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce1),
    .buf_r_q1(buf_r_q1),
    .RoundKey_val(RoundKey_val)
);

AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2 grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start),
    .ap_done(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done),
    .ap_idle(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_idle),
    .ap_ready(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_ready),
    .buf_r_address0(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address0),
    .buf_r_ce0(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce0),
    .buf_r_we0(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_we0),
    .buf_r_d0(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_d0),
    .buf_r_address1(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address1),
    .buf_r_ce1(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce1),
    .buf_r_q1(buf_r_q1),
    .sbox_address0(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_address0),
    .sbox_ce0(grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_ce0),
    .sbox_q0(sbox_q0)
);

AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_424_1 grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start),
    .ap_done(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done),
    .ap_idle(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_idle),
    .ap_ready(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_ready),
    .buf_r_load_9(buf_r_load_9_reg_639),
    .temp_2(temp_9_reg_597),
    .temp(temp_reg_534),
    .buf_r_load_14(buf_r_load_14_reg_675),
    .buf_r_load_10(buf_r_load_10_reg_644),
    .temp_1(temp_8_reg_576),
    .buf_r_load_2(buf_r_load_2_reg_560),
    .buf_r_load_13(buf_r_load_13_reg_670),
    .temp_3(temp_10_reg_618),
    .buf_r_load_6(buf_r_load_6_reg_602),
    .buf_r_load_1(buf_r_load_1_reg_555),
    .buf_r_load_12(buf_r_load_12_reg_665),
    .buf_r_load_8(buf_r_load_8_reg_623),
    .buf_r_load_4(buf_r_load_4_reg_581),
    .buf_r_load(buf_r_load_reg_539),
    .buf_r_load_11(buf_r_load_11_reg_660),
    .RoundKey_val(RoundKey_val),
    .p_out(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out),
    .p_out_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out_ap_vld),
    .p_out1(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1),
    .p_out1_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1_ap_vld),
    .p_out2(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2),
    .p_out2_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2_ap_vld),
    .t_3_out(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out),
    .t_3_out_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out_ap_vld),
    .p_out3(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3),
    .p_out3_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3_ap_vld),
    .p_out4(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4),
    .p_out4_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4_ap_vld),
    .p_out5(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5),
    .p_out5_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5_ap_vld),
    .t_2_out(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out),
    .t_2_out_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out_ap_vld),
    .p_out6(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6),
    .p_out6_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6_ap_vld),
    .p_out7(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7),
    .p_out7_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7_ap_vld),
    .p_out8(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8),
    .p_out8_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8_ap_vld),
    .t_1_out(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out),
    .t_1_out_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out_ap_vld),
    .p_out9(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9),
    .p_out9_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9_ap_vld),
    .p_out10(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10),
    .p_out10_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10_ap_vld),
    .p_out11(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11),
    .p_out11_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11_ap_vld),
    .t_out(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out),
    .t_out_ap_vld(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out_ap_vld),
    .sbox_address0(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address0),
    .sbox_ce0(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce0),
    .sbox_q0(sbox_q0),
    .sbox_address1(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address1),
    .sbox_ce1(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce1),
    .sbox_q1(sbox_q1),
    .sbox_address2(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address2),
    .sbox_ce2(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce2),
    .sbox_q2(sbox_q2),
    .sbox_address3(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address3),
    .sbox_ce3(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce3),
    .sbox_q3(sbox_q3),
    .sbox_address4(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address4),
    .sbox_ce4(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce4),
    .sbox_q4(sbox_q4),
    .sbox_address5(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address5),
    .sbox_ce5(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce5),
    .sbox_q5(sbox_q5),
    .sbox_address6(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address6),
    .sbox_ce6(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce6),
    .sbox_q6(sbox_q6),
    .sbox_address7(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address7),
    .sbox_ce7(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce7),
    .sbox_q7(sbox_q7),
    .sbox_address8(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address8),
    .sbox_ce8(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce8),
    .sbox_q8(sbox_q8),
    .sbox_address9(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address9),
    .sbox_ce9(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce9),
    .sbox_q9(sbox_q9),
    .sbox_address10(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address10),
    .sbox_ce10(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce10),
    .sbox_q10(sbox_q10),
    .sbox_address11(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address11),
    .sbox_ce11(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce11),
    .sbox_q11(sbox_q11),
    .sbox_address12(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address12),
    .sbox_ce12(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce12),
    .sbox_q12(sbox_q12),
    .sbox_address13(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address13),
    .sbox_ce13(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce13),
    .sbox_q13(sbox_q13),
    .sbox_address14(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address14),
    .sbox_ce14(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce14),
    .sbox_q14(sbox_q14),
    .sbox_address15(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address15),
    .sbox_ce15(grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce15),
    .sbox_q15(sbox_q15)
);

AES_ECB_encrypt_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22 grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start),
    .ap_done(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done),
    .ap_idle(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_idle),
    .ap_ready(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_ready),
    .buf_r_address0(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address0),
    .buf_r_ce0(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce0),
    .buf_r_we0(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_we0),
    .buf_r_d0(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_d0),
    .buf_r_address1(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address1),
    .buf_r_ce1(grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce1),
    .buf_r_q1(buf_r_q1),
    .RoundKey_val(RoundKey_val)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg <= 1'b1;
        end else if ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_ready == 1'b1)) begin
            grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg <= 1'b1;
        end else if ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_ready == 1'b1)) begin
            grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg <= 1'b1;
        end else if ((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_ready == 1'b1)) begin
            grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg <= 1'b1;
        end else if ((grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_ready == 1'b1)) begin
            grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_r_load_10_reg_644 <= buf_r_q0;
        buf_r_load_9_reg_639 <= buf_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_r_load_11_reg_660 <= buf_r_q1;
        buf_r_load_12_reg_665 <= buf_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        buf_r_load_13_reg_670 <= buf_r_q1;
        buf_r_load_14_reg_675 <= buf_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_r_load_1_reg_555 <= buf_r_q1;
        buf_r_load_2_reg_560 <= buf_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_r_load_4_reg_581 <= buf_r_q0;
        temp_8_reg_576 <= buf_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_r_load_6_reg_602 <= buf_r_q0;
        temp_9_reg_597 <= buf_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_r_load_8_reg_623 <= buf_r_q0;
        temp_10_reg_618 <= buf_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_r_load_reg_539 <= buf_r_q0;
        temp_reg_534 <= buf_r_q1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_address0 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_r_address0 = grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_r_address0 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address0;
    end else begin
        buf_r_address0 = buf_r_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        buf_r_address0_local = buf_r_addr_9_reg_592;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        buf_r_address0_local = buf_r_addr_3_reg_529;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        buf_r_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        buf_r_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        buf_r_address0_local = buf_r_addr_11_reg_613;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_r_address0_local = buf_r_addr_1_reg_518;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_r_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        buf_r_address0_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_r_address0_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_r_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_r_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_r_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_r_address0_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_r_address0_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_r_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_r_address0_local = 64'd5;
    end else begin
        buf_r_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_address1 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_r_address1 = grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_r_address1 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_address1;
    end else begin
        buf_r_address1 = buf_r_address1_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        buf_r_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        buf_r_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        buf_r_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        buf_r_address1_local = buf_r_addr_14_reg_649;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        buf_r_address1_local = buf_r_addr_6_reg_565;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_r_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_r_address1_local = buf_r_addr_4_reg_544;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        buf_r_address1_local = buf_r_addr_12_reg_628;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_r_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_r_address1_local = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_r_address1_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_r_address1_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_r_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_r_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_r_address1_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_r_address1_local = 64'd1;
    end else begin
        buf_r_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_ce0 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_r_ce0 = grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_r_ce0 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce0;
    end else begin
        buf_r_ce0 = buf_r_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_r_ce0_local = 1'b1;
    end else begin
        buf_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_ce1 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_r_ce1 = grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_r_ce1 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_ce1;
    end else begin
        buf_r_ce1 = buf_r_ce1_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_r_ce1_local = 1'b1;
    end else begin
        buf_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_d0 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_r_d0 = grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_r_d0 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_d0;
    end else begin
        buf_r_d0 = buf_r_d0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        buf_r_d0_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        buf_r_d0_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        buf_r_d0_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out3;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        buf_r_d0_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out5;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        buf_r_d0_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out6;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_r_d0_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out8;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_r_d0_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out9;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        buf_r_d0_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out11;
    end else begin
        buf_r_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        buf_r_d1_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        buf_r_d1_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_3_out;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        buf_r_d1_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out4;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        buf_r_d1_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_2_out;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        buf_r_d1_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out7;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_r_d1_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_1_out;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_r_d1_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_p_out10;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        buf_r_d1_local = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_t_out;
    end else begin
        buf_r_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_r_we0 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_buf_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_r_we0 = grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_buf_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_r_we0 = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_buf_r_we0;
    end else begin
        buf_r_we0 = buf_r_we0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15))) begin
        buf_r_we0_local = 1'b1;
    end else begin
        buf_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15))) begin
        buf_r_we1_local = 1'b1;
    end else begin
        buf_r_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_address0 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sbox_address0 = grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_address0;
    end else begin
        sbox_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce0 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sbox_ce0 = grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_sbox_ce0;
    end else begin
        sbox_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce1 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce1;
    end else begin
        sbox_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce10 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce10;
    end else begin
        sbox_ce10 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce11 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce11;
    end else begin
        sbox_ce11 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce12 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce12;
    end else begin
        sbox_ce12 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce13 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce13;
    end else begin
        sbox_ce13 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce14 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce14;
    end else begin
        sbox_ce14 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce15 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce15;
    end else begin
        sbox_ce15 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce2 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce2;
    end else begin
        sbox_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce3 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce3;
    end else begin
        sbox_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce4 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce4;
    end else begin
        sbox_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce5 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce5;
    end else begin
        sbox_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce6 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce6;
    end else begin
        sbox_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce7 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce7;
    end else begin
        sbox_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce8 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce8;
    end else begin
        sbox_ce8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sbox_ce9 = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_sbox_ce9;
    end else begin
        sbox_ce9 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign buf_r_addr_11_reg_613 = 64'd7;

assign buf_r_addr_12_reg_628 = 64'd0;

assign buf_r_addr_14_reg_649 = 64'd8;

assign buf_r_addr_1_reg_518 = 64'd5;

assign buf_r_addr_3_reg_529 = 64'd13;

assign buf_r_addr_4_reg_544 = 64'd2;

assign buf_r_addr_6_reg_565 = 64'd6;

assign buf_r_addr_9_reg_592 = 64'd15;

assign buf_r_d1 = buf_r_d1_local;

assign buf_r_we1 = buf_r_we1_local;

assign grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_22_fu_338_ap_start_reg;

assign grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start = grp_Cipher_Pipeline_VITIS_LOOP_240_1_VITIS_LOOP_242_2_fu_281_ap_start_reg;

assign grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start = grp_Cipher_Pipeline_VITIS_LOOP_254_1_VITIS_LOOP_256_2_fu_289_ap_start_reg;

assign grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start = grp_Cipher_Pipeline_VITIS_LOOP_424_1_fu_297_ap_start_reg;

endmodule //AES_ECB_encrypt_Cipher
